# Generated by Django 3.2 on 2021-04-29 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(default=datetime.datetime(2021, 4, 29, 6, 23, 30, 648, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
